config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: :index

  root to: 'home#index'
  get 'home/index'

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(controller)
    'active' if params[:controller] == controller
  end

  def markdown(&block)
    content = capture(&block)
    renderer = Redcarpet::Render::HTML
    Redcarpet::Markdown.new(renderer).render(content).html_safe
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <section class="jumbotron">
    <h1>Hello World</h1>
    <p>Just a new Rails app.</p>
  </section>
</div>

app/views/layouts/_footer.html.erb
<footer class="container">
  <div class="row text-small">
    <div class="col-md-10">
      &copy; <%= Time.now.year %> Rational Means
    </div>

    <div class="col-md-2 footer-col footer-follow">
      <div class="headline"><strong>Follow Us</strong></div>

      <a href="https://github.com/timcheadle"><i class="fa fa-github fa-2x"></i></a>
      <a href="https://twitter.com/timcheadle"><i class="fa fa-twitter fa-2x"></i></a>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Rails App', root_path, class: 'navbar-brand' %>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= is_active?('home') %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= is_active?('orders') %>"><%= link_to 'Orders', orders_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= content_for(:title) || "New Rails App" %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Orders</h1>
  </div>

  <table class="table">
    <thead>
      <th>Order #</th>
      <th>Customer</th>
      <th>Payment Status</th>
      <th>Fulfillment Status</th>
      <th>Total</th>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.name %></td>
          <td><%= order.customer %></td>
          <td><%= order.payment_status %></td>
          <td><%= order.fulfillment_status %></td>
          <td><%= order.total_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>